# Generated by Django 5.0.6 on 2024-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diskon',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Diskon %'),
        ),
    ]
