# Generated by Django 5.0.6 on 2024-06-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('website', '0003_custumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='website.custumer'),
        ),
    ]
