# Generated by Django 5.0.6 on 2024-06-24 11:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_transaksi_custumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tracking', models.DateField(null=True)),
                ('jam_tracking', models.CharField(max_length=50, null=True)),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('transaksi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.transaksi')),
            ],
            options={
                'verbose_name_plural': 'Tracking Transaksi',
            },
        ),
    ]
